FROM phusion/baseimage
RUN apt-get -y update && apt-get -y install python-pip && pip install supervisor
EXPOSE 9001
VOLUME /app
WORKDIR /app
ENV WORKER_NUM 4
#CMD ["/bin/bash",  "-c", "/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf"]
CMD ["/usr/local/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
